version: '3'

networks:
  elastic:
    name: elastic
    driver: bridge
    
volumes:
  elk-storage02:
    driver: local
  grafana-storage02:
    driver: local
    
services:
  elk02:
    container_name: elk02
    hostname: elasticsearch

    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
      
    environment:
      - discovery.type=single-node
       
    networks:
      - elastic
      
    volumes:
      - elk-storage02:/usr/share/elasticsearch/data
      
  heartbeat02:
    container_name: hb
      
    build:
      context: .
      dockerfile: dockerfile-heartbeat
      
    networks:
      - elastic
      
    depends_on: ['elk02']
      
  grafana02:
    image: grafana/grafana
    
    volumes:
      - grafana-storage02:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/dashboards/:/etc/grafana/dashboards/
      - ./grafana/provisioning:/etc/grafana/provisioning/
    
    networks:
      - elastic
      
    ports:
      - 80:3000
      
    depends_on: ['elk02']