version: '3'

networks:
  elastic:
    name: elastic
    driver: bridge
    
volumes:
  elk-storage:
    driver: local
  grafana-storage:
    driver: local

services:
  elk:
    container_name: elk01
    hostname: elasticsearch

    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
      
    environment:
      - discovery.type=single-node
       
    networks:
      - elastic
      
    ports:
      - 9200:9200
      
    volumes:
      - elk-storage:/usr/share/elasticsearch/data
      
  site_monitoring:
    container_name: site_monitoring
    
    build:
      context: .
      dockerfile: dockerfile-site_monitoring
      
    environment:
      CONF_FILE: site_monitoring.yml
      
    volumes:
      - ./site_monitoring.yml:/usr/src/app/site_monitoring.yml
      
    networks:
      - elastic
      
    depends_on: ['elk']
    
  grafana:
    image: grafana/grafana
    
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-config/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana-config/dashboards/:/etc/grafana/dashboards/
      - ./grafana-config/provisioning:/etc/grafana/provisioning/
    
    networks:
      - elastic
      
    ports:
      - 80:3000
      
    depends_on: ['elk']