{
 "title": "Site monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Status of InWebo site",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "Up",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "monitor.status: up && monitor.id: inwebo-status",
     "timeField": "@timestamp"
    },
    {
     "alias": "Down",
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "monitor.status: down && monitor.id: inwebo-status",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Status of Famira site",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "alias": "Up",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "monitor.status: up && monitor.id: famira-status",
     "timeField": "@timestamp"
    },
    {
     "alias": "Down",
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "monitor.status: down && monitor.id: famira-status",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "InWebo response time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Response duration" }
   ],
   "targets": [
    {
     "alias": "heartbeat*",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "monitor.duration.us", "id": "1", "settings": { "script": "_value / 1000" }, "type": "max" }
     ],
     "query": "monitor.id: inwebo-status",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Famira response time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Response duration" }
   ],
   "targets": [
    {
     "alias": "heartbeat*",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "monitor.duration.us", "id": "1", "settings": { "script": "_value / 1000" }, "type": "max" }
     ],
     "query": "monitor.id: famira-status",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}